import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import mjml2html from "mjml";
import ejs from "ejs";
const root = fileURLToPath(new URL("../src/email/templates/", import.meta.url));
const definitions = {
  "verify-email": [
    "Verify your email",
    "One more step to set up your NextPhish account.",
  ],
  "magic-link": [
    "Your secure sign-in link",
    "Sign in to your NextPhish workspace.",
  ],
  "password-reset": [
    "Reset your password",
    "Choose a new password for your account.",
  ],
  "organization-invitation": [
    "Your team is waiting",
    "You have been invited to a NextPhish organization.",
  ],
  "welcome-user": [
    "Welcome to NextPhish",
    "Set your password and join your team.",
  ],
  otp: ["Your verification code", "Use this code to continue securely."],
};
const keys = [
  "url",
  "appUrl",
  "name",
  "inviterName",
  "organizationName",
  "inviteLink",
  "magicLink",
  "otp",
];
const placeholders = Object.fromEntries(
  keys.map((key) => [key, `NP_EMAIL_TOKEN_${key}_END`]),
);
const master = await readFile(path.join(root, "master.mjml"), "utf8");
const compiled = {};
for (const [name, [title, preview]] of Object.entries(definitions)) {
  const body = ejs.render(
    await readFile(path.join(root, `${name}.mjml`), "utf8"),
    placeholders,
  );
  const source = ejs.render(master, { ...placeholders, title, preview, body });
  const result = await mjml2html(source, {
    validationLevel: "strict",
    ignoreIncludes: true,
    fonts: {},
  });
  let html = result.html;
  for (const key of keys)
    html = html.replaceAll(placeholders[key], `<%= ${key} %>`);
  compiled[name] = html;
}
const output = `// Generated by scripts/build-emails.mjs. Edit the MJML sources instead.\nexport const compiledTemplates = ${JSON.stringify(compiled, null, 2)} as const;\n`;
const outputPath = path.join(root, "compiled.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(outputPath, "utf8")) !== output)
    throw new Error(
      "Email templates are stale. Run pnpm --filter @next-phish/backend emails:build",
    );
} else await writeFile(outputPath, output);
const previewArg = process.argv.indexOf("--preview");
if (previewArg !== -1) {
  const destination = path.resolve(process.argv[previewArg + 1]);
  await mkdir(destination, { recursive: true });
  const demo = {
    url: "https://example.com/verify?token=" + "demo-token-".repeat(25),
    appUrl: "https://example.com",
    name: "Alex",
    inviterName: "Morgan",
    organizationName: "Acme Security",
    inviteLink: "https://example.com/invitation/demo",
    magicLink: "https://example.com/welcome/demo",
    otp: "482913",
  };
  for (const [name, html] of Object.entries(compiled))
    await writeFile(
      path.join(destination, `${name}.html`),
      ejs.render(html, demo),
    );
  await writeFile(
    path.join(destination, "index.html"),
    `<!doctype html><html lang="en"><meta name="viewport" content="width=device-width, initial-scale=1"><title>NextPhish email previews</title><body style="font:16px Arial;background:#f5f6fa;padding:40px;color:#192235"><h1>System email previews</h1><p>Demo data only. No email is sent.</p><ul>${Object.keys(
      compiled,
    )
      .map(
        (name) =>
          `<li style="margin:16px 0"><a href="${name}.html">${name}</a></li>`,
      )
      .join("")}</ul></body></html>`,
  );
}
console.log(`Validated ${Object.keys(compiled).length} MJML email templates.`);
